import { Product, ProductGroup } from "./types";

export const CATEGORIES: { name: ProductGroup; color: string }[] = [
  { name: "Weight Loss & Metabolic", color: "#3b82f6" }, // Blue
    { name: "Healing & Recovery", color: "#22c55e" }, // Green
      { name: "Growth Hormone & IGF", color: "#f97316" }, // Orange
        { name: "Anti-Aging & Longevity", color: "#a855f7" }, // Purple
          { name: "Sexual Health & Wellness", color: "#ec4899" }, // Pink
            { name: "Cognitive & Neuro", color: "#eab308" }, // Yellow
              { name: "Immune & Inflammation", color: "#ef4444" }, // Red
                { name: "Peptide Blends & Combos", color: "#14b8a6" }, // Teal
                ];

                const createProduct = (name: string, p1: number, p5: number, p10: number, p20: number, group: ProductGroup, mg: string = "10mg", coa?: Product['coa'], rating: number = 4.7, reviewCount: number = 89, image?: string): Product => ({
                  id: name.toLowerCase().replace(/\s+/g, '-'),
                    name,
                      description: `${name} is a high-purity research peptide synthesized for analytical evaluation. Professional grade lyophilized powder with >99% purity guaranteed. Validated via HPLC/MS for specialized biological observation. Not for human consumption.`,
                        prices: { 1: p1, 5: p5, 10: p10, 20: p20 },
                          group,
                            categoryColor: CATEGORIES.find(c => c.name === group)?.color || "#ffffff",
                              mg,
                                coa,
                                  rating,
                                    reviewCount,
                                      image: image || undefined
                                      });

                                      const DESCRIPTIONS: Record<string, string> = {
                                        "Retatrutide": "Retatrutide is a multi-receptor agonist targeting GIP, GLP-1, and glucagon receptors. This research-grade compound is synthesized for analytical studies investigating triple-agonist metabolic pathways and glucose regulation efficiency.",
                                          "Tirzepatide": "Tirzepatide is a dual GLP-1 and GIP receptor agonist. Our high-fidelity lyophilized peptide is engineered for precise measurement of dual-pathway metabolic activation and lipid metabolism profiling in laboratory environments.",
                                            "BPC-157": "BPC-157 (Body Protection Compound 157) is a pentadecapeptide derived from human gastric juice. This research material is optimized for in-vitro observation of angiogenic processes and cellular regenerative markers during laboratory trials.",
                                              "TB-500": "TB-500 is a synthetic version of Thymosin Beta-4. It is provided for analytical research into cellular migration, actin polymerization, and potential wound-healing signal pathways in controlled biological models.",
                                                "Semaglutide": "Semaglutide is a specialized GLP-1 receptor agonist. This analytic-grade peptide is designed for research applications focused on incretin mimetic effects and weight regulation signaling in biological systems.",
                                                  "Tesamorelin": "Tesamorelin is a growth hormone-releasing hormone (GHRH) analogue. Synthesized to >99% purity for investigating targeted growth hormone secretion and visceral adipose tissue research in clinical-adjacent models.",
                                                    "AOD-9604": "AOD9604 is a C-terminal fragment of the human growth hormone molecule. This research peptide is intended for focused investigations into lipolytic signaling without promoting systemic growth effects.",
                                                      "NAD+": "Nicotinamide Adenine Dinucleotide (NAD+) is an essential coenzyme for redox reactions. Our laboratory-stabilized formulation is prepared for observing cellular energy metabolism and DNA repair mechanism kinetics.",
                                                        "Ipamorelin": "Ipamorelin is a selective GHRP (Growth Hormone Releasing Peptide) agonist. This research-grade material allows for isolated observation of pulsatile growth hormone release without significant cortisol or prolactin activation.",
                                                        };

                                                        const getDesc = (name: string) => DESCRIPTIONS[name] || `${name} is a high-purity research peptide synthesized for analytical evaluation. Professional grade lyophilized powder with >99% purity guaranteed for specialized biological observation. Not for human consumption.`;

                                                        export const PRODUCTS: Product[] = [
                                                          // GROUP 1 — Weight Loss & Metabolic
                                                            // RETATRUTIDE
                                                              { ...createProduct("Retatrutide 5mg", 46, 211.60, 391, 717.60, "Weight Loss & Metabolic", "5mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                { ...createProduct("Retatrutide 10mg", 54, 248.40, 459, 842.40, "Weight Loss & Metabolic", "10mg", {
                                                                    taskNumber: "#70490",
                                                                        date: "08 JUL 2025",
                                                                            purity: "99.780%",
                                                                                content: "31.08 mg",
                                                                                    key: "9ESQLUYRP983"
                                                                                      }, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                        { ...createProduct("Retatrutide 15mg", 79, 363.40, 671.50, 1232.40, "Weight Loss & Metabolic", "15mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                          { ...createProduct("Retatrutide 20mg", 94, 432.40, 799, 1466.40, "Weight Loss & Metabolic", "20mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                            { ...createProduct("Retatrutide 30mg", 119, 547.40, 1011.50, 1856.40, "Weight Loss & Metabolic", "30mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                              { ...createProduct("Retatrutide 40mg", 149, 685.40, 1266.50, 2324.40, "Weight Loss & Metabolic", "40mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                                { ...createProduct("Retatrutide 50mg", 164, 754.40, 1394, 2558.40, "Weight Loss & Metabolic", "50mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },
                                                                                                  { ...createProduct("Retatrutide 60mg", 179, 823.40, 1521.50, 2792.40, "Weight Loss & Metabolic", "60mg", undefined, 4.7, 136), description: getDesc("Retatrutide") },

                                                                                                    // TIRZEPATIDE
                                                                                                      { ...createProduct("Tirzepatide 5mg", 32.20, 148.12, 273.70, 502.32, "Weight Loss & Metabolic", "5mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                        { ...createProduct("Tirzepatide 10mg", 57, 262.20, 484.50, 889.20, "Weight Loss & Metabolic", "10mg", {
                                                                                                            taskNumber: "#70489",
                                                                                                                date: "08 JUL 2025",
                                                                                                                    purity: "99.637%",
                                                                                                                        content: "31.33 mg",
                                                                                                                            key: "9SFDV8AW56HZ"
                                                                                                                              }, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                { ...createProduct("Tirzepatide 15mg", 57, 262.20, 484.50, 889.20, "Weight Loss & Metabolic", "15mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                  { ...createProduct("Tirzepatide 20mg", 61.60, 283.36, 523.60, 960.96, "Weight Loss & Metabolic", "20mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                    { ...createProduct("Tirzepatide 30mg", 64.40, 296.24, 547.40, 1004.64, "Weight Loss & Metabolic", "30mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                      { ...createProduct("Tirzepatide 40mg", 78.20, 359.72, 664.70, 1219.92, "Weight Loss & Metabolic", "40mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                        { ...createProduct("Tirzepatide 50mg", 87.40, 402.04, 742.90, 1363.44, "Weight Loss & Metabolic", "50mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },
                                                                                                                                          { ...createProduct("Tirzepatide 60mg", 101.20, 465.52, 860.20, 1578.72, "Weight Loss & Metabolic", "60mg", undefined, 4.9, 142), description: getDesc("Tirzepatide") },

                                                                                                                                            // SEMAGLUTIDE
                                                                                                                                              { ...createProduct("Semaglutide 5mg", 26.70, 122.82, 226.95, 416.52, "Weight Loss & Metabolic", "5mg", undefined, 4.8, 139), description: getDesc("Semaglutide") },
                                                                                                                                                { ...createProduct("Semaglutide 10mg", 26.70, 122.82, 226.95, 416.52, "Weight Loss & Metabolic", "10mg", undefined, 4.8, 139), description: getDesc("Semaglutide") },
                                                                                                                                                  { ...createProduct("Semaglutide 15mg", 54.30, 249.78, 461.55, 847.08, "Weight Loss & Metabolic", "15mg", undefined, 4.8, 139), description: getDesc("Semaglutide") },
                                                                                                                                                    { ...createProduct("Semaglutide 20mg", 72.70, 334.42, 617.95, 1134.12, "Weight Loss & Metabolic", "20mg", undefined, 4.8, 139), description: getDesc("Semaglutide") },
                                                                                                                                                      { ...createProduct("Semaglutide 30mg", 91.10, 419.06, 774.35, 1421.16, "Weight Loss & Metabolic", "30mg", undefined, 4.8, 139), description: getDesc("Semaglutide") },

                                                                                                                                                        // SURVODUTIDE
                                                                                                                                                          createProduct("Survodutide 10mg", 67.99, 312.75, 577.92, 1060.64, "Weight Loss & Metabolic", "10mg", undefined, 4.5, 74),

                                                                                                                                                            // MAZDUTIDE
                                                                                                                                                              createProduct("Mazdutide 10mg", 85, 391, 722.50, 1326, "Weight Loss & Metabolic", "10mg", undefined, 4.7, 83),

                                                                                                                                                                // CAGRILINTIDE
                                                                                                                                                                  createProduct("Cagrilintide 5mg", 36.80, 169.28, 312.80, 574.08, "Weight Loss & Metabolic", "5mg", undefined, 4.6, 98),
                                                                                                                                                                    createProduct("Cagrilintide 10mg", 59.80, 275.08, 508.30, 932.88, "Weight Loss & Metabolic", "10mg", undefined, 4.6, 98),

                                                                                                                                                                      // SEMA + CAGRI COMBO
                                                                                                                                                                        createProduct("Cagrilintide + Semaglutide 10mg", 90, 414, 765, 1404, "Weight Loss & Metabolic", "10mg", undefined, 4.8, 112),

                                                                                                                                                                          // AOD-9604
                                                                                                                                                                            { ...createProduct("AOD-9604 5mg", 49.99, 229.95, 424.92, 779.84, "Weight Loss & Metabolic", "5mg", undefined, 4.6, 91), description: getDesc("AOD-9604") },

                                                                                                                                                                              // 5-AMINO-1MQ
                                                                                                                                                                                createProduct("5-Amino-1MQ 5mg", 31.49, 144.85, 267.67, 491.54, "Weight Loss & Metabolic", "5mg", undefined, 4.3, 55),
                                                                                                                                                                                  createProduct("5-Amino-1MQ 50mg", 31.49, 144.85, 267.67, 491.54, "Weight Loss & Metabolic", "50mg", undefined, 4.3, 55),

                                                                                                                                                                                    // ADIPOTIDE
                                                                                                                                                                                      createProduct("Adipotide 5mg", 45, 207, 382.50, 702, "Weight Loss & Metabolic", "5mg", undefined, 4.4, 67),

                                                                                                                                                                                        // LEMON BOTTLE
                                                                                                                                                                                          createProduct("Lemon Bottle", 28.49, 131.01, 242.17, 444.32, "Weight Loss & Metabolic", "10mg", undefined, 4.7, 103),

                                                                                                                                                                                            // GROUP 2 — Healing & Recovery
                                                                                                                                                                                              // BPC-157
                                                                                                                                                                                                { ...createProduct("BPC-157 5mg", 23, 105.80, 195.50, 358.80, "Healing & Recovery", "5mg", {
                                                                                                                                                                                                    taskNumber: "#70491",
                                                                                                                                                                                                        date: "08 JUL 2025",
                                                                                                                                                                                                            purity: "99.755%",
                                                                                                                                                                                                                content: "14.04 mg",
                                                                                                                                                                                                                    key: "CGNEL1DPZYUQ"
                                                                                                                                                                                                                      }, 4.9, 187), description: getDesc("BPC-157") },
                                                                                                                                                                                                                        { ...createProduct("BPC-157 10mg", 25.70, 118.22, 218.45, 400.92, "Healing & Recovery", "10mg", undefined, 4.9, 187), description: getDesc("BPC-157") },

                                                                                                                                                                                                                          // TB-500
                                                                                                                                                                                                                            { ...createProduct("TB-500 5mg", 26.70, 122.82, 226.95, 416.52, "Healing & Recovery", "5mg", undefined, 4.8, 143), description: getDesc("TB-500") },
                                                                                                                                                                                                                              { ...createProduct("TB-500 10mg", 32.20, 148.12, 273.70, 502.32, "Healing & Recovery", "10mg", undefined, 4.8, 143), description: getDesc("TB-500") },

                                                                                                                                                                                                                                // BPC + TB STACKS
                                                                                                                                                                                                                                  createProduct("BPC-157 + TB-500 10mg", 40.80, 187.68, 346.80, 636.48, "Healing & Recovery", "10mg", {
                                                                                                                                                                                                                                      taskNumber: "#70494",
                                                                                                                                                                                                                                          date: "08 JUL 2025",
                                                                                                                                                                                                                                              purity: "Mixed Ratio",
                                                                                                                                                                                                                                                  content: "BPC 5.71mg / TB 5.44mg",
                                                                                                                                                                                                                                                      key: "YRQWW55JFKHI"
                                                                                                                                                                                                                                                        }, 4.9, 156),
                                                                                                                                                                                                                                                          createProduct("BPC-157 + TB-500 20mg", 55, 253, 467.50, 858, "Healing & Recovery", "20mg", undefined, 4.8, 128),

                                                                                                                                                                                                                                                            // GLOW STACK
                                                                                                                                                                                                                                                              createProduct("Glow Stack (BPC+GHK-Cu+TB)", 71.25, 327.75, 605.63, 1111.50, "Healing & Recovery", "70mg", {
                                                                                                                                                                                                                                                                  taskNumber: "#70495",
                                                                                                                                                                                                                                                                      date: "10 JUL 2025",
                                                                                                                                                                                                                                                                          purity: "99.612%",
                                                                                                                                                                                                                                                                              content: "72.1 mg",
                                                                                                                                                                                                                                                                                  key: "GLOW9XKPZMVW"
                                                                                                                                                                                                                                                                                    }, 4.7, 94),

                                                                                                                                                                                                                                                                                      // MULTI REPAIR STACK
                                                                                                                                                                                                                                                                                        createProduct("Multi Repair Stack", 63, 289.80, 535.50, 982.80, "Healing & Recovery", "80mg", undefined, 4.6, 77),

                                                                                                                                                                                                                                                                                          // KPV
                                                                                                                                                                                                                                                                                            createProduct("KPV 5mg", 31.49, 144.85, 267.67, 491.54, "Healing & Recovery", "5mg", undefined, 4.6, 77),
                                                                                                                                                                                                                                                                                              createProduct("KPV 10mg", 31.49, 144.85, 267.67, 491.54, "Healing & Recovery", "10mg", undefined, 4.6, 77),

                                                                                                                                                                                                                                                                                                // GROUP 3 — Growth Hormone & IGF
                                                                                                                                                                                                                                                                                                  // SERMORELIN
                                                                                                                                                                                                                                                                                                    createProduct("Sermorelin 5mg", 27.60, 126.96, 234.60, 430.56, "Growth Hormone & IGF", "5mg", undefined, 4.5, 86),
                                                                                                                                                                                                                                                                                                      createProduct("Sermorelin 10mg", 43.20, 198.72, 367.20, 673.92, "Growth Hormone & IGF", "10mg", undefined, 4.5, 86),

                                                                                                                                                                                                                                                                                                        // TESAMORELIN
                                                                                                                                                                                                                                                                                                          { ...createProduct("Tesamorelin 5mg", 39.60, 182.16, 336.60, 617.76, "Growth Hormone & IGF", "5mg", {
                                                                                                                                                                                                                                                                                                              taskNumber: "#70492",
                                                                                                                                                                                                                                                                                                                  date: "09 JUL 2025",
                                                                                                                                                                                                                                                                                                                      purity: "99.841%",
                                                                                                                                                                                                                                                                                                                          content: "10.22 mg",
                                                                                                                                                                                                                                                                                                                              key: "TESM3RLN4829"
                                                                                                                                                                                                                                                                                                                                }, 4.8, 109), description: getDesc("Tesamorelin") },
                                                                                                                                                                                                                                                                                                                                  { ...createProduct("Tesamorelin 10mg", 46, 211.60, 391, 717.60, "Growth Hormone & IGF", "10mg", undefined, 4.8, 109), description: getDesc("Tesamorelin") },

                                                                                                                                                                                                                                                                                                                                    // IPAMORELIN
                                                                                                                                                                                                                                                                                                                                      { ...createProduct("Ipamorelin 5mg", 27.60, 126.96, 234.60, 430.56, "Growth Hormone & IGF", "5mg", undefined, 4.8, 162), description: getDesc("Ipamorelin") },
                                                                                                                                                                                                                                                                                                                                        { ...createProduct("Ipamorelin 10mg", 32.20, 148.12, 273.70, 502.32, "Growth Hormone & IGF", "10mg", undefined, 4.8, 162), description: getDesc("Ipamorelin") },

                                                                                                                                                                                                                                                                                                                                          // HEXARELIN
                                                                                                                                                                                                                                                                                                                                            createProduct("Hexarelin 5mg", 23.24, 106.90, 197.54, 362.54, "Growth Hormone & IGF", "5mg", undefined, 4.6, 81),

                                                                                                                                                                                                                                                                                                                                              // GHRP FAMILY
                                                                                                                                                                                                                                                                                                                                                createProduct("GHRP-2 5mg", 25, 115, 212.50, 390, "Growth Hormone & IGF", "5mg", undefined, 4.4, 72),
                                                                                                                                                                                                                                                                                                                                                  createProduct("GHRP-6 5mg", 25, 115, 212.50, 390, "Growth Hormone & IGF", "5mg", undefined, 4.5, 88),
                                                                                                                                                                                                                                                                                                                                                    createProduct("GHRP-6 10mg", 35, 161, 297.50, 546, "Growth Hormone & IGF", "10mg", undefined, 4.5, 88),

                                                                                                                                                                                                                                                                                                                                                      // IGF / GROWTH FACTORS
                                                                                                                                                                                                                                                                                                                                                        createProduct("IGF-1 LR3 0.1mg", 20, 92, 170, 312, "Growth Hormone & IGF", "0.1mg", undefined, 4.7, 116),
                                                                                                                                                                                                                                                                                                                                                          createProduct("IGF-1 LR3 1mg", 60, 276, 510, 936, "Growth Hormone & IGF", "1mg", undefined, 4.7, 116),
                                                                                                                                                                                                                                                                                                                                                            createProduct("GDF-8 (Myostatin)", 80, 368, 680, 1248, "Growth Hormone & IGF", "10mg", undefined, 4.6, 61),

                                                                                                                                                                                                                                                                                                                                                              // MOTs-c
                                                                                                                                                                                                                                                                                                                                                                createProduct("MOTs-c 10mg", 32.72, 150.52, 278.12, 510.80, "Growth Hormone & IGF", "10mg", undefined, 4.7, 93),
                                                                                                                                                                                                                                                                                                                                                                  createProduct("MOTs-c 40mg", 32.72, 150.52, 278.12, 510.80, "Growth Hormone & IGF", "40mg", undefined, 4.7, 93),

                                                                                                                                                                                                                                                                                                                                                                    // SS-31
                                                                                                                                                                                                                                                                                                                                                                      createProduct("SS-31 10mg", 65, 299, 552.50, 1014, "Growth Hormone & IGF", "10mg", undefined, 4.6, 58),
                                                                                                                                                                                                                                                                                                                                                                        createProduct("SS-31 50mg", 65, 299, 552.50, 1014, "Growth Hormone & IGF", "50mg", undefined, 4.6, 58),

                                                                                                                                                                                                                                                                                                                                                                          // CJC variants — keeping existing
                                                                                                                                                                                                                                                                                                                                                                            createProduct("CJC-1295 No DAC", 50, 225, 400, 720, "Growth Hormone & IGF", "10mg", undefined, 4.7, 118),
                                                                                                                                                                                                                                                                                                                                                                              createProduct("CJC-1295 DAC", 60, 270, 480, 864, "Growth Hormone & IGF", "10mg", undefined, 4.6, 99),
                                                                                                                                                                                                                                                                                                                                                                                createProduct("CJC No DAC 5mg + IPA 5mg", 85, 382.50, 680, 1224, "Growth Hormone & IGF", "10mg", undefined, 4.9, 134),
                                                                                                                                                                                                                                                                                                                                                                                  createProduct("GHRP-2 / GHRP-6 Blend", 45, 202.50, 360, 648, "Growth Hormone & IGF", "10mg", undefined, 4.5, 67),

                                                                                                                                                                                                                                                                                                                                                                                    // GROUP 4 — Anti-Aging & Longevity
                                                                                                                                                                                                                                                                                                                                                                                      // NAD+
                                                                                                                                                                                                                                                                                                                                                                                        { ...createProduct("NAD+ 100mg", 20, 92, 170, 312, "Anti-Aging & Longevity", "100mg", undefined, 4.7, 133), description: getDesc("NAD+") },
                                                                                                                                                                                                                                                                                                                                                                                          { ...createProduct("NAD+ 500mg", 35.64, 163.94, 303.94, 558.86, "Anti-Aging & Longevity", "500mg", undefined, 4.7, 133), description: getDesc("NAD+") },
                                                                                                                                                                                                                                                                                                                                                                                            { ...createProduct("NAD+ 1000mg", 35.64, 163.94, 303.94, 558.86, "Anti-Aging & Longevity", "1000mg", undefined, 4.7, 133), description: getDesc("NAD+") },

                                                                                                                                                                                                                                                                                                                                                                                              // GHK-CU / AHK-CU
                                                                                                                                                                                                                                                                                                                                                                                                createProduct("GHK-Cu 50mg", 10, 46, 85, 156, "Anti-Aging & Longevity", "50mg", undefined, 4.8, 147),
                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("GHK-Cu 100mg", 13.60, 62.56, 115.60, 212.16, "Anti-Aging & Longevity", "100mg", undefined, 4.8, 147),
                                                                                                                                                                                                                                                                                                                                                                                                    createProduct("AHK-Cu 10mg", 45, 207, 382.50, 702, "Anti-Aging & Longevity", "10mg", undefined, 4.7, 133),

                                                                                                                                                                                                                                                                                                                                                                                                      // EPITALON
                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("Epitalon 10mg", 24.74, 113.85, 210.39, 386.09, "Anti-Aging & Longevity", "10mg", undefined, 4.8, 76),
                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("Epitalon 50mg", 25.49, 117.31, 216.78, 397.82, "Anti-Aging & Longevity", "50mg", undefined, 4.8, 76),

                                                                                                                                                                                                                                                                                                                                                                                                            // THYMALIN
                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("Thymalin 10mg", 34.49, 158.63, 293.67, 539.84, "Anti-Aging & Longevity", "10mg", undefined, 4.7, 88),

                                                                                                                                                                                                                                                                                                                                                                                                                // THYMOSIN ALPHA-1
                                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("Thymosin Alpha-1 5mg", 26.99, 124.15, 229.42, 421.72, "Anti-Aging & Longevity", "5mg", undefined, 4.7, 88),
                                                                                                                                                                                                                                                                                                                                                                                                                    createProduct("Thymosin Alpha-1 10mg", 26.99, 124.15, 229.42, 421.72, "Anti-Aging & Longevity", "10mg", undefined, 4.7, 88),

                                                                                                                                                                                                                                                                                                                                                                                                                      // PINEALON
                                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("Pinealon 5mg", 25, 115, 212.50, 390, "Anti-Aging & Longevity", "5mg", undefined, 4.4, 63),
                                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("Pinealon 10mg", 29.74, 136.71, 252.79, 463.82, "Anti-Aging & Longevity", "10mg", undefined, 4.4, 63),

                                                                                                                                                                                                                                                                                                                                                                                                                            // CEREBROLYSIN
                                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("Cerebrolysin 60ml", 55, 253, 467.50, 858, "Anti-Aging & Longevity", "60ml", undefined, 4.8, 76),

                                                                                                                                                                                                                                                                                                                                                                                                                                // GLUTATHIONE
                                                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("Glutathione", 26.24, 120.70, 223.04, 409.34, "Anti-Aging & Longevity", "10mg", undefined, 4.6, 119),

                                                                                                                                                                                                                                                                                                                                                                                                                                    // GROUP 5 — Sexual Health & Wellness
                                                                                                                                                                                                                                                                                                                                                                                                                                      createProduct("PT-141 (Bremelanotide)", 24.29, 111.73, 206.47, 379.54, "Sexual Health & Wellness", "10mg", undefined, 4.8, 138),
                                                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("MT-2 (Melanotan 2)", 45, 207, 382.50, 702, "Sexual Health & Wellness", "10mg", undefined, 4.6, 124),
                                                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("Melanotan 1", 50, 230, 425, 780, "Sexual Health & Wellness", "10mg", undefined, 4.5, 91),
                                                                                                                                                                                                                                                                                                                                                                                                                                            createProduct("Oxytocin 2mg", 18.74, 86.20, 159.29, 292.80, "Sexual Health & Wellness", "2mg", undefined, 4.7, 107),
                                                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("Kisspeptin-10 5mg", 20, 92, 170, 312, "Sexual Health & Wellness", "5mg", undefined, 4.6, 79),
                                                                                                                                                                                                                                                                                                                                                                                                                                                createProduct("Kisspeptin-10 10mg", 24.65, 113.39, 209.53, 384.06, "Sexual Health & Wellness", "10mg", undefined, 4.6, 79),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("Triptorelin", 25, 115, 212.50, 390, "Sexual Health & Wellness", "2mg", undefined, 4.5, 66),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    createProduct("HCG 5000iu", 45, 207, 382.50, 702, "Sexual Health & Wellness", "5000iu", undefined, 4.8, 143),
                                                                                                                                                                                                                                                                                                                                                                                                                                                      createProduct("HCG 10000iu", 90, 414, 765, 1404, "Sexual Health & Wellness", "10000iu", undefined, 4.8, 143),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("Insulin", 25, 115, 212.50, 390, "Sexual Health & Wellness", "10mg", undefined, 4.5, 82),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("Alprostadil", 65, 299, 552.50, 1014, "Sexual Health & Wellness", "20mg", undefined, 4.5, 66),

                                                                                                                                                                                                                                                                                                                                                                                                                                                            // GROUP 6 — Cognitive & Neuro
                                                                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("Selank 5mg", 21.25, 97.75, 180.63, 331.50, "Cognitive & Neuro", "5mg", undefined, 4.7, 112),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                createProduct("Selank 10mg", 21.25, 97.75, 180.63, 331.50, "Cognitive & Neuro", "10mg", undefined, 4.7, 112),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("Semax 5mg", 27.76, 127.70, 235.96, 433.14, "Cognitive & Neuro", "5mg", undefined, 4.7, 112),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    createProduct("Semax 10mg", 27.76, 127.70, 235.96, 433.14, "Cognitive & Neuro", "10mg", undefined, 4.7, 112),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      createProduct("Snap-8 (Acetyl Octapeptide)", 25.50, 117.30, 216.75, 397.80, "Cognitive & Neuro", "10mg", undefined, 4.6, 73),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("DSIP (Delta Sleep Peptide)", 50, 225, 400, 720, "Cognitive & Neuro", "10mg", undefined, 4.5, 84),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("SLU-PP-332", 90, 414, 765, 1404, "Cognitive & Neuro", "10mg", undefined, 4.7, 93),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // GROUP 7 — Immune & Inflammation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("LL-37", 75, 345, 637.50, 1170, "Immune & Inflammation", "10mg", undefined, 4.7, 96),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                createProduct("Ara-290", 29, 133.40, 246.50, 452.40, "Immune & Inflammation", "10mg", undefined, 4.8, 82),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  createProduct("ACE-031", 80, 368, 680, 1248, "Immune & Inflammation", "10mg", undefined, 4.6, 61),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // GROUP 8 — Peptide Blends & Combos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      createProduct("L-Carnitine 600mg", 55, 253, 467.50, 858, "Peptide Blends & Combos", "600mg", undefined, 4.6, 88),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        createProduct("Lipo-C + B12", 50, 230, 425, 780, "Peptide Blends & Combos", "10mg", undefined, 4.7, 71),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          createProduct("Hyaluronic Acid 5mg", 20, 92, 170, 312, "Peptide Blends & Combos", "5mg", undefined, 4.6, 58),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createProduct("HCG Bundle Kit (5000+10000iu)", 180, 810, 1440, 2592, "Peptide Blends & Combos", "Kit", undefined, 4.9, 167),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              createProduct("VIP (Vasoactive Intestinal)", 80, 360, 640, 1152, "Peptide Blends & Combos", "10mg", undefined, 4.7, 71),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                createProduct("CU50+TB10+BC10+KPV10 Stack", 180, 810, 1440, 2592, "Peptide Blends & Combos", "10mg", undefined, 4.9, 167),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];